##Spring Configuration
server: 
  port: 8080
  servlet:
    context-path: /testapirest
spring:
  application:
    name: test-api-rest

  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: 1234
    url: jdbc:h2:mem:testdb
    
  jpa:
     database-platform: org.hibernate.dialect.H2Dialect
#     hibernate:
#       ddl-auto: update
#     show-sql: false